[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyssam"
version = "0.2.3"
authors = [
  { name="Josh Williams" },
]
description = "A Python library for statistical modelling of biomedical shape and appearance"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
]
dependencies = [
  "numpy",
  "scikit_learn"
]

[project.optional-dependencies]
full = ["vedo", "trimesh", "networkx", "scikit_image"]

[tool.setuptools]
packages = ["pyssam"]

[project.urls]
"Homepage" = "https://github.com/jvwilliams23/pyssam"
"Bug Tracker" = "https://github.com/jvwilliams23/pyssam/issues"
